### ISSUE TITLE
preprocessing.get_ted_en2zhdefrjp_audio_manifest not present 

### ISSUE THREAD

**Issue by CharviVitthal** [fengpeng-yue/speech-to-speech-translation#4]
The first step in run_baseline.sh runs `preprocessing.get_ted_en2zhdefrjp_audio_manifest` but this file is not present in the code.

**Comment by dqqcasia** [comment]
> The first step in run_baseline.sh runs `preprocessing.get_ted_en2zhdefrjp_audio_manifest` but this file is not present in the code.

It appears that there is a missing file referenced in the script `run_baseline.sh`. I'll complete the missing file, then it should solve the issue in the script.

**Comment by dqqcasia** [comment]
> The first step in run_baseline.sh runs `preprocessing.get_ted_en2zhdefrjp_audio_manifest` but this file is not present in the code.

Refer to [commit](de21268983d8238514e32157d92d2694eaee89e9).
